dataset:
  sample_root: []
  lidar_variant: gicp
  cache_rasters: true
  max_translation_px: 4
  max_rotation_deg: 5
  train_fraction: 0.8

model:
  lidar_in_channels: 3
  map_in_channels: 5
  stem_channels: 32
  embed_dim: 64
  encoder_depth: 4
  encoder_base_channels: 64
  proj_dim: 4
  search_radius: 4
  theta_search_deg: 5
  translation_smoothing_kernel: 1
  gaussian_sigma_px: 1.0
  w_xy: 1.0
  w_theta: 1.0
  gaussian_sigma_theta_deg: 1.0
  sigma_weight_xy: 1.0
  sigma_weight_theta: 1.0

optim:
  lr: 0.0005
  weight_decay: 0.0001
  batch_size: 8
  num_workers: 2
  epochs: 400
  device: auto

save:
  enable: true
  save_dir: ./checkpoints
  save_best: true
  save_last: true
  monitor: val_loss
  mode: min
  filename_best: best_1000.ckpt
  filename_last: last_1000.ckpt

early_stop:
  enabled: true
  monitor: val_loss
  mode: min
  min_delta: 0.001
  patience: 50
  warmup_epochs: 20
  restore_best: true
